# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Reg2.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_RegWindow(object):
    def setupUi(self, RegWindow):
        RegWindow.setObjectName("RegWindow")
        RegWindow.resize(590, 730)
        RegWindow.setWindowTitle("Register")
        self.centralwidget = QtWidgets.QWidget(RegWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_order = QtWidgets.QPushButton(self.centralwidget)
        self.btn_order.setGeometry(QtCore.QRect(190, 670, 93, 28))
        self.btn_order.setObjectName("btn_order")
        self.btn_cancel = QtWidgets.QPushButton(self.centralwidget)
        self.btn_cancel.setGeometry(QtCore.QRect(310, 670, 93, 28))
        self.btn_cancel.setObjectName("btn_cancel")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(0, 0, 590, 647))
        self.tableWidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setProperty("showDropIndicator", True)
        self.tableWidget.setDragEnabled(False)
        self.tableWidget.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.tableWidget.setAlternatingRowColors(False)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.tableWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setWordWrap(True)
        self.tableWidget.setCornerButtonEnabled(True)
        self.tableWidget.setRowCount(15)
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(78, 156, 214))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(78, 156, 214))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(207, 238, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(207, 238, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(207, 238, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(207, 238, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(207, 238, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(207, 238, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 1, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(207, 238, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(207, 238, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(7, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 1, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(207, 238, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(207, 238, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(9, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(10, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(10, 1, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(207, 238, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(11, 0, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(207, 238, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(11, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(12, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(12, 1, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(207, 238, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(13, 0, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(207, 238, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget.setItem(13, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(14, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(14, 1, item)
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(294)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(30)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(43)
        self.tableWidget.verticalHeader().setHighlightSections(True)
        self.tableWidget.verticalHeader().setMinimumSectionSize(30)
        RegWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(RegWindow)
        self.statusbar.setObjectName("statusbar")
        RegWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(RegWindow)
        self.actionExit.setObjectName("actionExit")

        self.retranslateUi(RegWindow)
        QtCore.QMetaObject.connectSlotsByName(RegWindow)

    def retranslateUi(self, RegWindow):
        _translate = QtCore.QCoreApplication.translate
        self.btn_order.setText(_translate("RegWindow", "送出預約"))
        self.btn_cancel.setText(_translate("RegWindow", "取消"))
        self.tableWidget.setSortingEnabled(False)
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("RegWindow", "場地預約"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("RegWindow", "申請編號"))
        item = self.tableWidget.item(1, 1)
        item.setText(_translate("RegWindow", "(1, 1) lbl_bookSeq"))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("RegWindow", "申請場地"))
        item = self.tableWidget.item(2, 1)
        item.setText(_translate("RegWindow", "(2, 1) lbl_placeName"))
        item = self.tableWidget.item(3, 0)
        item.setText(_translate("RegWindow", "申請狀態"))
        item = self.tableWidget.item(3, 1)
        item.setText(_translate("RegWindow", "(3, 1) lbl_placeState"))
        item = self.tableWidget.item(4, 0)
        item.setText(_translate("RegWindow", "申請人資料"))
        item = self.tableWidget.item(4, 1)
        item.setText(_translate("RegWindow", "(4, 1) lbl_memberName"))
        item = self.tableWidget.item(5, 0)
        item.setText(_translate("RegWindow", "聯絡人"))
        item = self.tableWidget.item(5, 1)
        item.setText(_translate("RegWindow", "(5, 1)"))
        item = self.tableWidget.item(6, 0)
        item.setText(_translate("RegWindow", "聯絡人電話"))
        item = self.tableWidget.item(6, 1)
        item.setText(_translate("RegWindow", "(6, 1)"))
        item = self.tableWidget.item(7, 0)
        item.setText(_translate("RegWindow", "聯絡人傳真"))
        item = self.tableWidget.item(7, 1)
        item.setText(_translate("RegWindow", "(7, 1)"))
        item = self.tableWidget.item(8, 0)
        item.setText(_translate("RegWindow", "Email"))
        item = self.tableWidget.item(8, 1)
        item.setText(_translate("RegWindow", "(8, 1)"))
        item = self.tableWidget.item(9, 0)
        item.setText(_translate("RegWindow", "收費種類"))
        item = self.tableWidget.item(9, 1)
        item.setText(_translate("RegWindow", "(9, 1) lbl_payType"))
        item = self.tableWidget.item(10, 0)
        item.setText(_translate("RegWindow", "收費方式"))
        item = self.tableWidget.item(10, 1)
        item.setText(_translate("RegWindow", "(10, 1) lbl_payMethod"))
        item = self.tableWidget.item(11, 0)
        item.setText(_translate("RegWindow", "預約日期"))
        item = self.tableWidget.item(11, 1)
        item.setText(_translate("RegWindow", "(11, 1) lbl_date"))
        item = self.tableWidget.item(12, 0)
        item.setText(_translate("RegWindow", "預約時段"))
        item = self.tableWidget.item(12, 1)
        item.setText(_translate("RegWindow", "(12, 1) lbl_time"))
        item = self.tableWidget.item(13, 0)
        item.setText(_translate("RegWindow", "預約場地數"))
        item = self.tableWidget.item(13, 1)
        item.setText(_translate("RegWindow", "(13, 1) lbl_placeNum"))
        item = self.tableWidget.item(14, 0)
        item.setText(_translate("RegWindow", "場地收費標準"))
        item = self.tableWidget.item(14, 1)
        item.setText(_translate("RegWindow", "(14, 1) lbl_payStand"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.actionExit.setText(_translate("RegWindow", "Exit"))
        self.actionExit.setShortcut(_translate("RegWindow", "Esc"))

